name: orb_example
description: Demonstrates how to use the orb plugin.

# Don't publish to pub.dev using `pub publish`.
publish_to: none

environment:
  sdk: '>=2.10.5 <3.0.0'
  flutter: '>=2.2.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  orb:
    path: ../

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
