name: orb_module
description: |
  A Flutter module to integrate the Orb Mobile SDK into an existing Android or
  iOS app.
version: 2.7.8

# Don't publish to pub.dev using `pub publish`.
publish_to: none


environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=2.4.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  orb:
    path: ../orb

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  module:
    androidX: true
    androidPackage: ai.meya.orb_module
    iosBundleIdentifier: ai.meya.orbModule
