include: package:flutter_lints/flutter.yaml
linter:
  rules:
    always_put_control_body_on_new_line: true
    always_put_required_named_parameters_first: true
    always_use_package_imports: true
    avoid_dynamic_calls: true
    avoid_field_initializers_in_const_classes: true
    avoid_positional_boolean_parameters: true
    avoid_slow_async_io: true
    avoid_type_to_string: true
    avoid_types_on_closure_parameters: true
    eol_at_end_of_file: true
    invariant_booleans: true
    prefer_final_in_for_each: true
    prefer_final_locals: true
    prefer_null_aware_method_calls: true
    prefer_single_quotes: true
    require_trailing_commas: true
    sized_box_shrink_expand: true
    unnecessary_late: true
    unnecessary_parenthesis: true
    unnecessary_statements: true
    use_build_context_synchronously: true
    use_decorated_box: true
    use_named_constants: true
