name: orb
description: Orb Mobile SDK for Android and iOS
version: 2.8.0

# Don't publish to pub.dev using `pub publish`.
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=2.4.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  collection: ^1.15.0
  file_picker: ^3.0.1
  flutter_secure_storage: ^4.1.0
  flutter_svg: ^0.21.0
  google_fonts: ^2.0.0
  http: ^0.13.1
  image_picker: ^0.7.4
  flutter_linkify: ^5.0.2
  flutter_markdown: ^0.6.4
  mime: ^1.0.0
  msgpack_dart: ^1.0.0
  package_info_plus: ^1.0.0
  path: ^1.8.0
  platform: ^3.1.0
  provider: ^5.0.0
  separated_column: ^2.0.0
  separated_row: ^2.0.0
  url_launcher: ^6.0.3
  uuid: ^3.0.3
  web_socket_channel: ^2.0.0

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
  import_sorter: ^4.6.0

flutter:
  uses-material-design: true

  assets:
    - icons/

  plugin:
    platforms:
      android:
        package: ai.meya.orb
        pluginClass: OrbPlugin
      ios:
        pluginClass: OrbPlugin

import_sorter:
  comments: false
